# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Specific headers for JavaScript and TypeScript files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
